healthcare_pipeline:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: /config/workspace/case_study/healthcare-pipeline/data/healthcare.db
      schema: main
      schema_directory: /config/workspace/case_study/healthcare-pipeline/healthcare_pipeline_dbt/models
      schemas_and_paths:
        main: /config/workspace/case_study/healthcare-pipeline/data/healthcare.db
