#!/bin/bash
python run_patients_validations.py
python run_medications_validations.py
python run_conditions_validations.py
python run_symptoms_validations.py
python run_patients_gender_validations.py
python run_encounters_validations.py